### ISSUE TITLE
Json dump of solver.config_dict() fails with TypeError: Object of type Subset is not JSON serializable | in train_set

### ISSUE THREAD

**Issue by schinto** [DeepGraphLearning/torchdrug#40] opened 2021-09-22 11:48 UTC
torchdrug.version: 0.1.1

### Code
```python
import json
import torch
from torchdrug import core, datasets, tasks, models

dataset = datasets.OPV("~/molecule-datasets/")
train_set, valid_set, test_set = dataset.split()
print(f"# Train/Valid/Test: {len(train_set)}/{len(valid_set)}/{len(test_set)}")

model = models.GIN(
    input_dim=dataset.node_feature_dim,
    hidden_dims=[300, 300, 300, 300],
    short_cut=True,
    batch_norm=True,
    concat_hidden=True,
)
subtasks = (
    "gap",
    "homo",
    "lumo",
    "spectral_overlap",
)
task = tasks.PropertyPrediction(
    model, task=subtasks, criterion="mse", metric=("mae", "rmse"), verbose=1
)
optimizer = torch.optim.Adam(task.parameters(), lr=1e-3)
solver = core.Engine(
    task,
    train_set,
    valid_set,
    test_set,
    optimizer,
    gpus=[0],
    batch_size=256,
)
with open("opv_gin.json", "w") as fout:
    json.dump(solver.config_dict(), fout)
```

### Error
```
Traceback (most recent call last):
  File "~/opv-gin-property-prediction.py", line 40, in <module>
    json.dump(solver.config_dict(), fout)
  File "~/opt/anaconda3/envs/drugs/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "~/opt/anaconda3/envs/drugs/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "~/opt/anaconda3/envs/drugs/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "~/opt/anaconda3/envs/drugs/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "~/opt/anaconda3/envs/drugs/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Subset is not JSON serializable
```

### Output JSON File
`opv_gin.json`
```json
{
    "class": "core.Engine",
    "task": {
        "class": "tasks.PropertyPrediction",
        "model": {
            "class": "models.GIN",
            "input_dim": 69,
            "hidden_dims": [
                300,
                300,
                300,
                300
            ],
            "edge_input_dim": null,
            "num_mlp_layer": 2,
            "eps": 0,
            "learn_eps": false,
            "short_cut": true,
            "batch_norm": true,
            "activation": "relu",
            "concat_hidden": true,
            "readout": "sum"
        },
        "task": [
            "gap",
            "homo",
            "lumo",
            "spectral_overlap"
        ],
        "criterion": "mse",
        "metric": [
            "mae",
            "rmse"
        ],
        "verbose": 1
    },
    "train_set":
```
Writing of the file `opv_gin.json` stops with the error above.

**Comment by KiddoZhu** [comment] 2021-09-22 14:19
Duplicate of #26. Fixed in `0.1.1.post1`.

**Closed** 2021-09-26 04:31 UTC
Labels: duplicate
