### ISSUE TITLE
An issue on Retrosynthesis Tasks

### ISSUE THREAD

**Issue by w1u2d3i4** [DeepGraphLearning/torchdrug#43] opened 2021-09-29 06:51 UTC
synthon_optimizer = torch.optim.Adam(synthon_task.parameters(), lr=1e-3)
synthon_solver = core.Engine(synthon_task, synthon_train, synthon_valid,
                             synthon_test, synthon_optimizer,
                             gpus=[0], batch_size=128)
**synthon_solver.train(num_epoch=10)**
synthon_solver.evaluate("valid")
synthon_solver.save("g2gs_synthon_model.pth")
![image](https://user-images.githubusercontent.com/45423717/135217471-e5e2a319-fbde-44d1-8cd2-b313bb6d5869.png)

**Comment by KiddoZhu** [comment] 2021-09-29 07:00
Thanks for interest in TorchDrug. This is duplicate of #42 and has been fixed. Please checkout the latest repo. Note conda/pip packages may have some lag, since we can't afford releasing a package for every bug fix.

**Comment by w1u2d3i4** [comment] 2021-09-29 08:14
So the code on github is right now?

**Comment by w1u2d3i4** [comment] 2021-09-29 09:23
Thanks a lot for solving my problem

**Closed** 2021-10-01 04:23 UTC
Labels: duplicate
